//arrays de productos 
const productos = [
    {id:1, nombre:"Remera Peace Gris", descripcion:"No hay que complicar las cosas. Los detalles en contraste convierten esta remera sencilla en algo único. Su tejido es tan suave que seguramente no te la vas a querer quitar.Nuestros productos de algodón apoyan el cultivo de algodón sostenible. Esto hace parte de nuestro anhelo de ponerle fin a la contaminación por plástico.", precio:3000, imagen:"../asset/img/remera1.webp", categoria:"remeras"},
    {id:2, nombre:"Remera STUFF Blanca", descripcion:"La confección en tejido de punto simple asegura una sensación suave y cómoda para los días de paseo o para cualquier día. Nuestros productos de algodón apoyan el cultivo de algodón sostenible.", precio:3000, imagen:"../asset/img/remera2.webp", categoria:"remeras"},
    {id:3, nombre:"Remera Rolling Azul", descripcion:"Cuando la naturaleza llama, vos respondés (o al menos lo intentás). Incluso si no podés darte una escapada al momento, tenés esta remera adidas para acompañarte mientras planificás tu próxima aventura. Te brinda comodidad inigualable gracias a su corte holgado y a su tejido de algodón supersuave. Nuestros productos de algodón apoyan el cultivo de algodón sostenible.", precio:3000, imagen:"../asset/img/remera3.jpg", categoria:"remeras"},
    {id:4, nombre:"Remera THANK YOU Negra", descripcion:" Confeccionada con un suave estampado de caucho y un cómodo tejido de punto de algodón, esta camiseta está lista para acompañarte en el día a día. Al comprar nuestros productos de algodón apoyas un cultivo de algodón más sostenible.", precio:3000, imagen:"../asset/img/remera4.webp", categoria:"remeras"},
    {id:5, nombre:"Remera Rolling Roja", descripcion:"Cuando la naturaleza llama, vos respondés (o al menos lo intentás). Incluso si no podés darte una escapada al momento, tenés esta remera adidas para acompañarte mientras planificás tu próxima aventura. Te brinda comodidad inigualable gracias a su corte holgado y a su tejido de algodón supersuave. Nuestros productos de algodón apoyan el cultivo de algodón sostenible.", precio:3000, imagen:"../asset/img/remera5.jpg", categoria:"remeras"},
    {id:6, nombre:"Buzo TEDDY Gris ", descripcion:"Las noches frescas y las mañanas frías requieren del abrigo y la comodidad de este buzo con capucha . No hay nada mejor que envolverte con la suavidad que ofrece el tejido de felpa francesa de este buzo con capucha. Este producto está hecho con material reciclado como parte de nuestro anhelo de ponerle fin a la contaminación por plástico. Nuestros productos de algodón apoyan el cultivo de algodón sostenible. Esto hace parte de nuestro anhelo de ponerle fin a la contaminación por plástico.", precio:500, imagen:"../asset/img/buzo1.jpg", categoria:"buzos"},
    {id:7, nombre:"Buzo ROMA Verde ", descripcion:"Este es para los amantes de los buzos con capucha, los que saben que nunca podés equivocarte con esta prenda, es simplemente perfecta. Detalles clásicos incluyen el dobladillo y los puños acanalados y el infaltable bolsillo canguro. Está hecho de felpa francesa que ofrece una sensación de lujo insuperable. Este producto está hecho con material reciclado como parte de nuestro anhelo de ponerle fin a la contaminación por plástico Nuestros productos de algodón apoyan el cultivo de algodón sostenible. Esto hace parte de nuestro anhelo de ponerle fin a la contaminación por plástico.", precio:7000, imagen:"../asset/img/buzo2.jpg", categoria:"buzos"},
    {id:8, nombre:"Buzo WAFLE Gris ", descripcion:"El cambio de clima viene acompañado de cambios en tu clóset. Aprovechá la oportunidad y envolvete en la comodidad de este buzo y enfrentate al aire frío con un estilo sofisticado y minimalista. Un pequeño logo del Trifolio le imprime una dosis de orgullo a la marca. Al comprar nuestros productos de algodón apoyas un cultivo de algodón más sostenible. Este producto incorpora material reciclado como parte de nuestro anhelo de ponerle fin a la contaminación por plástico", precio:7000, imagen:"../asset/img/buzo3.jpg", categoria:"buzos"},
    {id:9, nombre:"Buzo TOMORROW Beige ", descripcion:" Como es de esperarse de NINETY 90 , la felpa ofrece la combinación perfecta de suavidad y ligereza. Se ve genial sobre un pantalón o unos jeans. Usá este cómodo diseño de cuello redondo en el camino a tu entrenamiento, o para encargarse de tu lista de cosas pendientes por hacer. Esta prenda fue confeccionada utilizando UNITEFIT, un sistema de ajuste para todos los géneros que fue creado pensando en una gran variedad de tamaños, géneros y formas. Producto hecho parcialmente con contenido reciclado generado a partir de desechos de producción, tales como recortes de tela y desechos domésticos posconsumo, para evitar un mayor impacto ambiental al producir contenido virgen.", precio:7000, imagen:"../asset/img/buzo4.webp", categoria:"buzos"},
    {id:10, nombre:"Buzo TEDDY Verde ", descripcion:"Las noches frescas y las mañanas frías requieren del abrigo y la comodidad de este buzo con capucha . No hay nada mejor que envolverte con la suavidad que ofrece el tejido de felpa francesa de este buzo con capucha. Este producto está hecho con material reciclado como parte de nuestro anhelo de ponerle fin a la contaminación por plástico. Nuestros productos de algodón apoyan el cultivo de algodón sostenible. Esto hace parte de nuestro anhelo de ponerle fin a la contaminación por plástico.", precio:7000, imagen:"../asset/img/buzo5.jpg", categoria:"buzos"},
    {id:11, nombre:"Jean JONA ", descripcion:"Este jean hace que vestir con estilo sea fácil. Solo ponetelo y salí a la calle. Sabés que lucirás bien y te sentirás bien porque su diseño minimalista en felpa francesa se encarga de ambas cosas en un instante. Nuestros productos de algodón apoyan el cultivo de algodón sostenible.", precio:10000, imagen:"../asset/img/pantalon1.jpg", categoria:"desayuno-merienda"},
    {id:12, nombre:"Jogger NAHOY Gris", descripcion:"Este pantalón hace que vestir con estilo sea fácil. Solo ponetelo y salí a la calle. Sabés que lucirás bien y te sentirás bien porque su diseño minimalista en felpa francesa se encarga de ambas cosas en un instante. Nuestros productos de algodón apoyan el cultivo de algodón sostenible.", precio:10000, imagen:"../asset/img/pantalon2.jpg", categoria:"desayuno-merienda"}
];

const guardarProductosLS = (productos) => {
    localStorage.setItem("productos", JSON.stringify(productos));
}

const cargarProductosLS = () => {
    return JSON.parse(localStorage.getItem("productos")) || [];
}

guardarProductosLS(productos);